### ISSUE TITLE
labuladong的算法小抄 删除了大佬您的热心评论

### ISSUE THREAD

**Issue by Tisfy** [LetMeFly666/LeetCode#1]
当时有闻大佬给labuladong评论使其网址蓬荜生辉，今见彼人删除了大佬您的热心评论，瞬感愤慨万分，故来此向大佬报告！

![0](https://user-images.githubusercontent.com/88925368/172627818-83a78de4-bd8c-471b-98d1-25ce5f2757dc.jpg)

**Comment by Tisfy** [comment]
看别人都评论了什么！

![1](https://user-images.githubusercontent.com/88925368/172631669-21453b44-a564-47e4-83cf-ffc8b5fce2bd.jpg)

他可能是怕大佬您太强一句友善的评论吸走他的小粉儿。

**Comment by LetMeFly666** [comment]
倒是也没有关系。

不营销，用心写题解就够了。

**Comment by Tisfy** [comment]
Thank you for approval!
See you!
