### ISSUE TITLE
寻求合作

### ISSUE THREAD

**Issue by specialzxw** [LetMeFly666/LeetCode#8]
hello，这里是蓝桥云课（www.lanqiao.cn），冒昧联系，我们看到您常常刷题分享题解，看得出您对算法很熟悉，所以我们想邀请您合作。我们平台作为蓝桥杯的官方在线平台，近期计划为蓝桥杯备赛题库（https://www.lanqiao.cn/problems/?first_category_id=1&sort=students_count）中新增一批 oj 题，现对外招募【竞赛教练/有获奖经验的同学】参加出题，每题单价 50-120 元！我们想邀请您参与，如果您近期时间充裕，有兴趣尝试，欢迎填写表单 https://lanqiao-courses.feishu.cn/share/base/form/shrcng7A6oOJRhMAFpRSEcBbbhh 报名，我们 24 小时内将会通过微信联系您，发送出题资料，进行 1 道题目的试写。

**Comment by LetMeFly666** [comment]
很高兴您能关注到此项目。消息已收到，谢谢。

**Comment by LetMeFly666** [comment]
很高兴您能关注到此项目。消息已收到，谢谢。

请问您是“推荐人”吗？若报名，推荐人应如何填写？

**Comment by LetMeFly666** [comment]
👌
